Add logs & signup test

diff --git a/rootfs/etc/cont-init.d/01-checks b/rootfs/etc/cont-init.d/01-checks
--- a/rootfs/etc/cont-init.d/01-checks
+++ b/rootfs/etc/cont-init.d/01-checks
@@ -5,40 +5,49 @@ EXITCODE=0
 
 # BeastHost
 if [ -z "${BEAST_HOST}" ]; then
-  echo -e "ERROR: BEAST_HOST environment variable not set"
+  echo "ERROR: BEAST_HOST environment variable not set"
   exit 1
 fi
 # FR24Key and Signup
 if [ -z "${FR24_KEY}" ]; then
-  echo -e "WARNING: FR24_KEY environment variable was not set, try to signup to FR24"
+  if [ -s "/FR24_KEY" ]; then
+    KEY_VAL=$(cat /FR24_KEY)
+    echo "INFO: Signup already processed."
+    echo "INFO: Please restart the container with environment variable FR24_KEY=$KEY_VAL environment variable"
+    echo "INFO: You can remove FR24_MAIL, LATITUDE, LONGITUDE & ALTITUDE environment variable"
+    #exit 1
+  fi
+  
+  echo "WARNING: FR24_KEY environment variable was not set, try to signup to FR24"
+  rm -f /etc/fr24feed.ini
   # Mail
   if [ -z "${FR24_MAIL}" ]; then
-    echo -e "ERROR: FR24_KEY & FR24_MAIL environment variable was not set!"
+    echo "ERROR: FR24_KEY & FR24_MAIL environment variable was not set!"
     EXITCODE=1
   else
     if ! echo "${FR24_MAIL}" | grep -P '^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$' > /dev/null 2>&1; then
-      echo -e "ERROR: FR24_MAIL is not a valid email address!"
+      echo "ERROR: FR24_MAIL is not a valid email address!"
       EXITCODE=1      
     fi
   fi
   # LATITUDE
   if [ -z "${LATITUDE}" ]; then
-    echo -e "ERROR: FR24_KEY & LATITUDE environment variable not set!"
+    echo "ERROR: FR24_KEY & LATITUDE environment variable not set!"
     EXITCODE=1
   fi
   # LONGITUDE
   if [ -z "${LONGITUDE}" ]; then
-    echo -e "ERROR: FR24_KEY & LONGITUDE environment variable not set!"
+    echo "ERROR: FR24_KEY & LONGITUDE environment variable not set!"
     EXITCODE=1
   fi
   # ALTITUDE
   if [ -z "${ALTITUDE}" ]; then
-    echo -e "ERROR: FR24_KEY & ALTITUDE environment variable not set!"
+    echo "ERROR: FR24_KEY & ALTITUDE environment variable not set!"
     EXITCODE=1
   fi
   # ERROR ?
   if [ $EXITCODE -gt 0 ]; then
-    echo -e "ERROR: see behind for list of errors!"
+    echo "ERROR: see behind for list of errors!"
     exit 1
   fi
   # Signup Vars
@@ -93,7 +102,7 @@ if [ -z "${FR24_KEY}" ]; then
   } > "$TMPFILE"
   # Run Scrpit
   if ! expect "$TMPFILE" > "$TMPLOG" 2>&1; then
-    echo -e "ERROR: Problem running sign-up process"
+    echo "ERROR: Problem running sign-up process"
     echo ""
     cat "$TMPLOG"
     exit 1
@@ -105,9 +114,10 @@ if [ -z "${FR24_KEY}" ]; then
   NB_LINE_KEY=$(grep -Pc "$REGEX_KEY" "$TMPLOG")
   if [ "$NB_LINE_KEY" -gt 0 ]; then
     FR24_NEWKEY=$(grep -P "$REGEX_KEY" "$TMPLOG" | sed -r "s/$REGEX_KEY/\1/")
-    echo -e "FR24_KEY=$FR24_NEWKEY"
+    echo "FR24_KEY=$FR24_NEWKEY"
+    printf "%s" "$FR24_NEWKEY" > /FR24_KEY
   else
-    echo -e "ERROR: Could not find sharing key"
+    echo "ERROR: Could not find sharing key"
     echo ""
     cat "$TMPLOG"
     exit 1
@@ -116,9 +126,10 @@ if [ -z "${FR24_KEY}" ]; then
   NB_LINE_ID=$(grep -Pc "$REGEX_RADAR_ID" "$TMPLOG")
   if [ "$NB_LINE_ID" -gt 0 ]; then
     FR24_RID=$(grep -P "$REGEX_RADAR_ID" "$TMPLOG" | sed -r "s/$REGEX_RADAR_ID/\1/")
-    echo -e "RADAR_ID=$FR24_RID"
+    echo "RADAR_ID=$FR24_RID"
+    printf "%s" "$FR24_RID" > /FR24_RID
   else
-    echo -e "ERROR: Could not find Radar ID"
+    echo "ERROR: Could not find Radar ID"
     echo ""
     cat "$TMPLOG"
     exit 1
@@ -128,12 +139,12 @@ if [ -z "${FR24_KEY}" ]; then
   printf "%s" "$FR24_NEWKEY" > /var/run/s6/container_environment/FR24_KEY
   # Inform User
   echo ""
-  echo -e "INFO: Please restart the container with environment variable FR24_KEY=$FR24_NEWKEY environment variable"
-  echo -e "You can remove FR24_MAIL, LATITUDE, LONGITUDE & ALTITUDE environment variable"
+  echo "INFO: Please restart the container with environment variable FR24_KEY=$FR24_NEWKEY environment variable"
+  echo "You can remove FR24_MAIL, LATITUDE, LONGITUDE & ALTITUDE environment variable"
 else
   # FR24_KEY & signup env variables
   if [ -n "${FR24_MAIL}" ] || [ -n "${LATITUDE}" ] || [ -n "${LONGITUDE}" ] || [ -n "${ALTITUDE}" ]; then
-    echo -e "FR24_MAIL, LATITUDE, LONGITUDE & ALTITUDE environment variable are not used when FR24_KEY is provided"
+    echo "FR24_MAIL, LATITUDE, LONGITUDE & ALTITUDE environment variable are not used when FR24_KEY is provided"
   fi
 fi
 
